#! /bin/sh

# Copyright (c) Istituto Nazionale di Fisica Nucleare (INFN). 2006-2010.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

common=$1

mkdir -p src/autogen project rpm/tmp
set -x

if [ -d ../$common/m4 ]; then
  aclocal -I project -I ../$common/m4
elif [ -d ../../$common/m4 ]; then
  aclocal -I project -I ../../$common/m4
elif [ -d ../../../$common/m4 ]; then
  aclocal -I project -I ../../../$common/m4
else
  aclocal -I project
fi

libtoolize --force
autoheader
automake --foreign --add-missing --copy
autoconf
