apiVersion: v1
kind: Pod
metadata:
    labels:
        ci-job: build-storm-gridftp-dsi
spec:
    nodeSelector:
        zone: ci
    volumes:
      - name: ssh
        secret:
            secretName: jenkins-ssh-keys
    containers:
      - name: kube-storm-build
        image: italiangrid/storm-build:centos6
        imagePullPolicy: Always
        command:
          - cat
        tty: true
        volumeMounts:
          - name: ssh
            mountPath: /home/jenkins/.ssh
        resources:
            limits:
                memory: 700Mi
                cpu: 1
      - name: jnlp
        resources:
            limits:
                memory: 700Mi
                cpu: 1
    restartPolicy: Never
